language: ruby

before_install:
   - rvm install 3.0.0

services:
  - postgresql

before_script:
  - psql -U postgres -c 'CREATE DATABASE peep_manager_test;'

script:
  - bundle exec rake create_tables
  - bundle exec rspec
